[package]
name = "navius-db"
version = "0.1.0"
edition = "2024"
authors = ["Evan Coleman"]
description = "Database functionality for the Navius framework"
license = "Apache-2.0"
repository = "https://github.com/Evan-Coleman/Navius"
readme = "README.md"
keywords = ["database", "orm", "navius"]
categories = ["database"]

[features]
default = ["postgres"]
postgres = []

[dependencies]
# Core dependencies
navius-core = { path = "../../crates/navius-core", version = "0.1.0" }
# navius-test = { path = "../../crates/navius-test", version = "0.1.0" }
async-trait = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
sqlx = { workspace = true, features = ["postgres", "runtime-tokio-native-tls"] }

[dev-dependencies]
mockall = "0.13.1"
