image: rust:latest

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  MDBOOK_VERSION: "0.4.36"

stages:
  - deploy

# Documentation job to build the mdbook
pages:
  stage: deploy
  image: rust:latest
  variables:
    GIT_DEPTH: "1"
  script:
    - cargo install mdbook --version ${MDBOOK_VERSION} --no-default-features
    - cargo install mdbook-mermaid --version 0.12.6
    - cd docs
    - mdbook build
    - mkdir -p ../public
    - cp -r book/* ../public/
  artifacts:
    paths:
      - public
  cache:
    key: mdbook-cache
    paths:
      - $CARGO_HOME/bin/
      - $CARGO_HOME/.crates.toml
      - $CARGO_HOME/.crates2.json
  rules:
    # Run only when commit message contains [build-docs]
    - if: '$CI_COMMIT_MESSAGE =~ /\[build-docs\]/'
      when: always
    # Otherwise, manual trigger
    - when: manual

# Only run the pipeline manually or with specific commit message
workflow:
  rules:
    # Run pipeline when commit message contains [build-docs]
    - if: '$CI_COMMIT_MESSAGE =~ /\[build-docs\]/'
      when: always
    # Run pipeline on manual trigger for any branch
    - if: '$CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api" || $CI_PIPELINE_SOURCE == "trigger"'
      when: always 