# Example configuration file for Petstore API Server
# Copy this file to config.yaml and modify as needed

# Server configuration
server:
  host: "0.0.0.0"  # Listen on all interfaces
  port: 3000       # Port to listen on

# External API endpoints
api:
  cat_fact_url: "https://catfact.ninja/fact"
  petstore_url: "https://petstore3.swagger.io/api/v3"

# Application settings
app:
  name: "Petstore API Server"
  version: "1.0.0"
  log_level: "info"  # Possible values: trace, debug, info, warn, error 