name: Navius Status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-status:
    name: Build Status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Verify build
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features
      - name: Run basic tests (lightweight)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features -- --test-threads=1 --skip="integration_"
      
  lint-status:
    name: Lint Status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
          
  badge-generator:
    name: Update Status Badges
    needs: [build-status, lint-status]
    runs-on: ubuntu-latest
    steps:
      - name: Create Build Passing Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: navius-build.json
          label: Build
          message: Passing
          color: green
      - name: Create Version Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: navius-version.json
          label: Version
          message: v0.1.0
          color: blue 