# Default configuration file
# These settings can be overridden by environment-specific files or environment variables
# 
# Environment variable overrides follow these patterns:
# - SERVER_* for server settings
# - API_* for API settings
# - APP_* for app settings
# - AUTH_* for auth settings
# - RUST_BACKEND_* for Entra ID specific settings

server:
  host: "0.0.0.0"
  port: 3000
  timeout_seconds: 10
  max_retries: 3
  protocol: "http"

api:
  petstore_url: "https://petstore3.swagger.io/api/v3"
  api_key: null

app:
  name: "Petstore API Server"
  version: "1.0.0"
  log_level: "info"

# Authentication settings
auth:
  # Enable/disable authentication (override with AUTH_ENABLED)
  enabled: false
  # Enable/disable debug mode (override with AUTH_DEBUG or DEBUG_AUTH)
  debug: false
  # Entra ID (Azure AD) settings
  # The following values must be set through environment variables:
  # - RUST_BACKEND_TENANT_ID
  # - RUST_BACKEND_CLIENT_ID
  # - RUST_BACKEND_AUDIENCE
  # - RUST_BACKEND_SCOPE
  # - RUST_BACKEND_TOKEN_URL
  entra:
    # URL formats for Entra ID (Microsoft Azure AD)
    jwks_uri_format: "https://login.microsoftonline.com/{}/discovery/v2.0/keys"
    authorize_url_format: "https://login.microsoftonline.com/{}/oauth2/v2.0/authorize"
    token_url_format: "https://login.microsoftonline.com/{}/oauth2/v2.0/token"
    # Issuer URL formats (used for validation)
    issuer_url_formats:
      - "https://login.microsoftonline.com/{}/v2.0"
      - "https://login.microsoftonline.com/{}/v2.0/"
      - "https://sts.windows.net/{}"
      - "https://sts.windows.net/{}/"
      - "https://login.microsoftonline.com/{}"
      - "https://login.microsoftonline.com/{}/"
    # Admin roles - users with these roles can access admin endpoints
    admin_roles:
      - "admin"
    # Read-only roles - users with these roles can access read-only endpoints
    read_only_roles:
      - "read"
      - "full"
      - "admin"
    # Full access roles - users with these roles can access full access endpoints
    full_access_roles:
      - "full"

cache:
  enabled: true
  ttl_seconds: 300
  max_capacity: 1000 

# Reference to reliability settings
# Detailed configuration in reliability.yaml
reliability:
  enabled: true

# OpenAPI configuration
openapi:
  spec_file: "rust-backend.yaml"

logging:
  level: "info"
  format: "json"
