server:
  host: "0.0.0.0"
  port: 3000
  timeout_seconds: 10
  max_retries: 3

api:
  cat_fact_url: "https://catfact.ninja/fact"
  petstore_url: "https://petstore3.swagger.io/api/v3"
  api_key: null

app:
  name: "Petstore API Server"
  version: "1.0.0"
  log_level: "info"

cache:
  enabled: true
  ttl_seconds: 300
  max_capacity: 1000 

logging:
  response_fields:
    cat_fact_fields: 
      - fact
      - length
      # Don't include length if you don't want it
    health_fields:
      - status
      - uptime_seconds
    api_response_fields:
      - code
      - message 
