# Default configuration file
# These settings can be overridden by environment-specific files or environment variables
# 
# Environment variable overrides follow these patterns:
# - SERVER_* for server settings
# - API_* for API settings
# - APP_* for app settings
# - AUTH_* for auth settings
# - RUST_BACKEND_* for Entra ID specific settings

server:
  host: "0.0.0.0"
  port: 3000
  timeout_seconds: 10
  max_retries: 3

api:
  cat_fact_url: "https://catfact.ninja/fact"
  petstore_url: "https://petstore3.swagger.io/api/v3"
  api_key: null

app:
  name: "Petstore API Server"
  version: "1.0.0"
  log_level: "info"

# Authentication settings
auth:
  # Enable/disable authentication (override with AUTH_ENABLED)
  enabled: true
  # Enable/disable debug mode (override with AUTH_DEBUG or DEBUG_AUTH)
  debug: false
  # Entra ID (Azure AD) settings
  # The following values must be set through environment variables:
  # - RUST_BACKEND_TENANT_ID
  # - RUST_BACKEND_CLIENT_ID
  # - RUST_BACKEND_AUDIENCE
  # - RUST_BACKEND_SCOPE
  # - RUST_BACKEND_TOKEN_URL
  entra:
    # Default permission - can be overridden with RUST_BACKEND_PERMISSION
    permission: "default-rust-backend"
    # Admin roles - users with these roles can access admin endpoints
    admin_roles:
      - "admin"
      - "pet-manager"
    # Read-only roles - users with these roles can access read-only endpoints
    read_only_roles:
      - "reader"
      - "viewer"
    # Full access roles - users with these roles can access full access endpoints
    full_access_roles:
      - "editor"
      - "contributor"

cache:
  enabled: true
  ttl_seconds: 300
  max_capacity: 1000 

# Reference to reliability settings
# Detailed configuration in reliability.yaml
reliability:
  enabled: true

logging:
  response_fields:
    cat_fact_fields: 
      - fact
      - length
      # Don't include length if you don't want it
    health_fields:
      - status
      - uptime_seconds
    api_response_fields:
      - code
      - message 
