# Development environment configuration
# Overrides settings from default.yaml for development environments
# 
# In development mode, debug features are enabled by default
# See default.yaml for all available settings and environment variable overrides

server:
  # Use localhost for development
  host: "127.0.0.1"
  # More frequent retries in development
  max_retries: 5

app:
  # More verbose logging in development
  log_level: "debug"

cache:
  # Shorter TTL for development to see changes faster
  ttl_seconds: 60

# Environment-specific authentication settings
auth:
  enabled: true
  # Debug mode enables simplified token validation for easier testing
  debug: true 