# Development environment configuration
# Overrides settings from default.yaml for development environments
# 
# In development mode, debug features are enabled by default
# See default.yaml for all available settings and environment variable overrides

server:
  # Use localhost for development
  host: "127.0.0.1"
  # More frequent retries in development
  max_retries: 5
  # Use HTTP protocol for development
  protocol: "http"

app:
  # More verbose logging in development
  log_level: "debug"

# API configuration
api:
  base_url: "http://localhost:3000"
  version: "1.0.0"
  timeout_seconds: 30

cache:
  enabled: true
  # ttl_seconds: 300
  # max_capacity: 1000
  # reconnect_interval_seconds: 30

# Database configuration
database:
  enabled: false
  url: "${DATABASE_URL}"
  max_connections: 10
  connect_timeout_seconds: 30
  idle_timeout_seconds: 300

# # Environment-specific authentication settings
# auth:
#   enabled: true
#   # Debug mode enables simplified token validation for easier testing
#   debug: true
#   default_provider: "entra"
#   providers:
#     entra:
#       enabled: true
#       role_mappings:
#         admin: ["admin", "pet-manager", "developer"]
#         read_only: ["reader", "viewer", "tester"]
#         full_access: ["editor", "contributor", "developer"] 