# Development environment configuration
# Overrides settings from default.yaml for development environments
# 
# In development mode, debug features are enabled by default
# See default.yaml for all available settings and environment variable overrides

server:
  # Use localhost for development
  host: "127.0.0.1"
  # More frequent retries in development
  max_retries: 5
  # Use HTTP protocol for development
  protocol: "http"

app:
  # More verbose logging in development
  log_level: "debug"

cache:
  enabled: true
  # ttl_seconds: 300
  # max_capacity: 1000
  # reconnect_interval_seconds: 30

# Database configuration
database:
  enabled: true
  url: "postgres://postgres:postgres@localhost:5432/app"
  max_connections: 10
  connect_timeout_seconds: 30
  idle_timeout_seconds: 300

# # Environment-specific authentication settings
# auth:
#   enabled: true
#   # Debug mode enables simplified token validation for easier testing
#   debug: false
#   # Entra ID settings for development
#   entra:
#     # Admin roles for development - can include additional test roles
#     admin_roles:
#       - "admin"
#       - "pet-manager"
#       - "developer"
#     # Read-only roles for development
#     read_only_roles:
#       - "reader"
#       - "viewer"
#       - "tester"
#     # Full access roles for development
#     full_access_roles:
#       - "editor"
#       - "contributor"
#       - "developer" 