# Development environment configuration
# Overrides settings from default.yaml for development environments
# 
# In development mode, debug features are enabled by default
# See default.yaml for all available settings and environment variable overrides

server:
  # Use localhost for development
  host: "127.0.0.1"
  # More frequent retries in development
  max_retries: 5
  # Use HTTP protocol for development
  protocol: "http"

app:
  # More verbose logging in development
  log_level: "debug"

cache:
  # Shorter TTL for development to see changes faster
  ttl_seconds: 60

# Environment-specific authentication settings
auth:
  enabled: true
  # Debug mode enables simplified token validation for easier testing
  debug: true 
  # Entra ID settings for development
  entra:
    # Admin roles for development - can include additional test roles
    admin_roles:
      - "admin"
      - "pet-manager"
      - "developer"
    # Read-only roles for development
    read_only_roles:
      - "reader"
      - "viewer"
      - "tester"
    # Full access roles for development
    full_access_roles:
      - "editor"
      - "contributor"
      - "developer" 