# Production environment configuration
# Overrides settings from default.yaml for production environments
# 
# In production mode, security features are fully enabled
# Performance settings are optimized for production loads
# See default.yaml for all available settings and environment variable overrides

server:
  # Longer timeout for production
  timeout_seconds: 30
  # Fewer retries in production to fail faster
  max_retries: 2

app:
  # Less verbose logging in production
  log_level: "info"

cache:
  # Longer TTL for production for better performance
  ttl_seconds: 3600
  # Larger cache capacity for production
  max_capacity: 10000

# Environment-specific authentication settings
auth:
  # Authentication is always enabled in production
  enabled: true
  # Debug authentication is disabled in production for security
  debug: false 