# Production environment configuration
server:
  # Longer timeout for production
  timeout_seconds: 30
  # Fewer retries in production to fail faster
  max_retries: 2

app:
  # Less verbose logging in production
  log_level: "info"

cache:
  # Longer TTL for production for better performance
  ttl_seconds: 3600
  # Larger cache capacity for production
  max_capacity: 10000 