// Use navius-core for core functionality
use navius_core::{
    // config::Config as NaviusConfig, // Keep commented out until config type fixed
    di::{Application, ApplicationBuilder},
    error::Result,
};

// Use navius-http for server config and middleware stubs
use axum::Router;

// Import the necessary macros
use navius_macros::nest;

// Other necessary imports
use std::net::SocketAddr;
use std::sync::Arc;
use tracing::{debug, error, info, Level};

// Config imports
use config::Config as ExternalConfig;

#[tokio::main]
async fn main() -> Result<()> {
    // Initialize tracing with debug level
    tracing_subscriber::fmt()
        .with_max_level(Level::DEBUG)
        .init();
    info!("Tracing initialized with debug level.");

    // --- Configuration ---
    let temp_config: ExternalConfig = ExternalConfig::builder()
        .add_source(config::File::with_name("config/default.toml").required(false))
        .add_source(config::File::with_name("config/local.toml").required(false))
        .add_source(config::Environment::with_prefix("NAVIUS").separator("__"))
        .build()
        .map_err(|e| {
            error!("Configuration error: {}", e);
            navius_core::error::Error::configuration(format!("Config build error: {}", e))
        })?;
    info!("Configuration loaded.");

    // --- Application Context & DI ---
    info!("Initializing application builder...");
    // TODO: Use ApplicationBuilder::with_config once config type mismatch is resolved
    let app_builder = ApplicationBuilder::new();
    info!("Application builder created.");

    // --- JWT Provider (Placeholder) ---
    // TODO: Fix unresolved type errors (E0412, E0433) and uncomment
    // let jwt_config = temp_config.get::<TokenProviderConfig>("jwt")?;
    // let jwt_provider = Arc::new(JWTProvider::new("jwt_main".to_string(), jwt_config));
    // app_builder.add_component(jwt_provider)?;
    // info!("JWT Provider registered.");

    // --- REMOVED: Database Pool ---

    // --- REMOVED: Repository ---

    // --- Build Application Context & State ---
    info!("Building application...");
    let app: Application = app_builder.build();
    let app_arc = Arc::new(app);
    // Restore original AppState
    let app_state = AppState {
        app: app_arc.clone(),
    };
    info!("Application built and state created.");

    // --- Router Setup ---
    // The router function generated by the #[nest] macro
    let api_router = api::__navius_router_api();

    // Create a new router instance with application state
    // Use the api module's __NAVIUS_NEST_PREFIX for proper nesting
    let app_router = Router::new()
        .nest(
            format!("/api{}", api::__NAVIUS_NEST_PREFIX).as_str(),
            api_router,
        )
        .with_state(app_state);

    info!("Router setup complete.");

    // --- Server Start ---
    info!("Setting up server address...");
    let host = match temp_config.get_string("server.host") {
        Ok(h) => {
            info!("Config provided host: {}", h);
            h
        }
        Err(e) => {
            info!("No host in config ({}), using default: 127.0.0.1", e);
            "127.0.0.1".to_string()
        }
    };

    let port = match temp_config.get_int("server.port") {
        Ok(p) => {
            info!("Config provided port: {}", p);
            p as u16
        }
        Err(e) => {
            info!("No port in config ({}), using default: 3001", e);
            3001u16
        }
    };

    // Parse socket address safely
    let addr: SocketAddr = match format!("{}:{}", host, port).parse() {
        Ok(addr) => addr,
        Err(e) => {
            error!("Failed to parse address: {}", e);
            "127.0.0.1:3001".parse().unwrap() // Changed fallback to 3001
        }
    };

    info!("Server configured to listen on {}", addr);
    info!("Starting HTTP server...");

    // Create a TCP listener with more detailed error handling
    debug!("Attempting to bind TCP listener to {}", addr);
    let listener = match tokio::net::TcpListener::bind(addr).await {
        Ok(l) => {
            info!("Successfully bound to {}", addr);
            l
        }
        Err(e) => {
            error!("Failed to bind to address: {}", e);
            return Err(navius_core::error::Error::internal(format!(
                "Failed to bind to address: {}",
                e
            )));
        }
    };

    info!("Server listening on http://{}", addr);
    info!("Press Ctrl+C to stop the server");

    // Run the server with more detailed error handling
    debug!("Starting axum::serve");
    match axum::serve(listener, app_router).await {
        Ok(_) => {
            info!("Server shut down gracefully");
        }
        Err(e) => {
            error!("Server error: {}", e);
            return Err(navius_core::error::Error::internal(format!(
                "Server error: {}",
                e
            )));
        }
    }

    info!("Server shutdown complete.");
    Ok(())
}

// API Module
#[nest(prefix = "/v1")]
mod api {
    use super::*;
    use axum::extract::State;

    // Import the trait needed for registry methods
    use navius_core::di::registry::ComponentRegistry;

    #[route(method = "GET", path = "/hello")]
    pub async fn hello_world() -> &'static str {
        info!("Hello World");
        "Hello, world!"
    }

    // Keep context_info handler as it uses the core DI registry
    #[route(method = "GET", path = "/context")]
    #[axum::debug_handler]
    async fn context_info(State(state): State<AppState>) -> String {
        // Access registry through AppState -> Application, lock, then call method
        format!(
            "Components: {:?}",
            state.app.registry().lock().unwrap().component_types()
        )
    }
}

// Application state
#[derive(Clone, Debug)]
struct AppState {
    app: Arc<Application>,
}
