// Use navius-core for core functionality
use navius_core::{
    // config::Config as NaviusConfig, // Keep commented out until config type fixed
    di::{Application, ApplicationBuilder},
    error::Result,
};

// Use navius-http for server config and middleware stubs
use axum::Router;

// Import the necessary macros
use navius_macros::nest;

// Other necessary imports
use std::net::SocketAddr;
use std::sync::Arc;
use tracing::info;

// Config imports
use config::Config as ExternalConfig;

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt::init();
    info!("Tracing initialized.");

    // --- Configuration ---
    let temp_config: ExternalConfig = ExternalConfig::builder()
        .add_source(config::File::with_name("config/default.toml").required(false))
        .add_source(config::File::with_name("config/local.toml").required(false))
        .add_source(config::Environment::with_prefix("NAVIUS").separator("__"))
        .build()
        .map_err(|e| {
            navius_core::error::Error::configuration(format!("Config build error: {}", e))
        })?;
    info!("Configuration loaded.");

    // --- Application Context & DI ---
    info!("Initializing application builder...");
    // TODO: Use ApplicationBuilder::with_config once config type mismatch is resolved
    let mut app_builder = ApplicationBuilder::new();
    info!("Application builder created.");

    // --- JWT Provider (Placeholder) ---
    // TODO: Fix unresolved type errors (E0412, E0433) and uncomment
    // let jwt_config = temp_config.get::<TokenProviderConfig>("jwt")?;
    // let jwt_provider = Arc::new(JWTProvider::new("jwt_main".to_string(), jwt_config));
    // app_builder.add_component(jwt_provider)?;
    // info!("JWT Provider registered.");

    // --- REMOVED: Database Pool ---

    // --- REMOVED: Repository ---

    // --- Build Application Context & State ---
    info!("Building application...");
    let app: Application = app_builder.build();
    let app_arc = Arc::new(app);
    // Restore original AppState
    let app_state = AppState {
        app: app_arc.clone(),
    };
    info!("Application built and state created.");

    // --- Router Setup ---
    // The router function generated by the #[nest] macro
    let api_router = api::__navius_router_api();

    // Create a new router instance with application state
    let app_router: Router<AppState> = Router::new().nest("/api", api_router).with_state(app_state);

    info!("Router setup complete.");

    // --- Server Start ---
    info!("Setting up server address...");
    let host = temp_config
        .get_string("server.host")
        .unwrap_or_else(|_| "127.0.0.1".to_string());
    let port = temp_config.get_int("server.port").unwrap_or(8080) as u16;

    // Parse socket address safely
    let addr: SocketAddr = match format!("{}:{}", host, port).parse() {
        Ok(addr) => addr,
        Err(e) => {
            info!("Failed to parse address: {}", e);
            "127.0.0.1:8080".parse().unwrap()
        }
    };

    info!("Server configured to listen on {}", addr);

    // Handle shutdown - this is a simplified implementation
    let listener = tokio::net::TcpListener::bind(addr).await.map_err(|e| {
        navius_core::error::Error::internal(format!("Failed to bind to address: {}", e))
    })?;

    info!("Server listening on {}", addr);
    info!("Server running at http://{}. Press Ctrl+C to stop.", addr);

    // Wait for Ctrl+C signal without starting the server
    // In a real implementation, we would process connections here
    tokio::signal::ctrl_c()
        .await
        .expect("Failed to listen for Ctrl+C signal");

    info!("Shutdown signal received. Server shutting down...");
    info!("Server shutdown complete.");
    Ok(())
}

// API Module
#[nest(prefix = "/v1")]
mod api {
    use super::*;
    use axum::extract::State;
    use navius_macros::route;
    // Import the trait needed for registry methods
    use navius_core::di::registry::ComponentRegistry;

    #[route(method = "GET", path = "/hello")]
    pub async fn hello_world() -> &'static str {
        "Hello, world!"
    }

    // Keep context_info handler as it uses the core DI registry
    #[route(method = "GET", path = "/context")]
    #[axum::debug_handler]
    async fn context_info(State(state): State<AppState>) -> String {
        // Access registry through AppState -> Application, lock, then call method
        format!(
            "Components: {:?}",
            state.app.registry().lock().unwrap().component_types()
        )
    }
}

// Application state
#[derive(Clone, Debug)]
struct AppState {
    app: Arc<Application>,
}
