name: Documentation Validation

on:
  push:
    paths:
      - 'docs/**'
  pull_request:
    paths:
      - 'docs/**'

jobs:
  validate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Create markdownlint config
        run: |
          cat > .markdownlint.json << EOF
          {
            "default": true,
            "MD013": false,
            "MD033": false,
            "MD041": false
          }
          EOF

      - name: Run markdownlint
        run: markdownlint 'docs/**/*.md'

      - name: Check for broken links
        run: |
          npm install -g markdown-link-check
          find docs -name "*.md" -exec markdown-link-check {} \;

      - name: Validate metadata headers
        run: |
          #!/bin/bash
          EXIT_CODE=0
          for file in $(find docs -name "*.md"); do
            if ! grep -q "^---$" "$file"; then
              echo "Error: Missing frontmatter in $file"
              EXIT_CODE=1
              continue
            fi
            
            # Check required metadata fields
            for field in "title" "description" "category" "tags" "last_updated" "version"; do
              if ! grep -q "^$field:" "$file"; then
                echo "Error: Missing required field '$field' in $file"
                EXIT_CODE=1
              fi
            done
          done
          exit $EXIT_CODE
        shell: bash 